[pytest]
addopts = --html=reports/html_report.html --self-contained-html -v
testpaths = tests
markers =
    smoke: Smoke test suite
    regression: Regression test suite
    login: Login module tests
    employee: Employee module tests
    payroll: Payroll module tests
    attendance: Attendance module tests
